name: Build ubuntu18.04-release

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run: git submodule update --init
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.101
    - name: Build with dotnet
      run: dotnet publish src/Miki/Miki.csproj --configuration Release
    - name: Run tests with dotnet
      run: dotnet test test/Miki.Tests/Miki.Tests.csproj
